export const PERMISSIONS = {
  // USER
  USER_READ: 'USER_READ',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_RESTORE: 'USER_RESTORE',

  // ROLE
  ROLE_READ: 'ROLE_READ',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',

  // PERMISSION
  PERMISSION_READ: 'PERMISSION_READ',
  ROLE_PERMISSION_ASSIGN: 'ROLE_PERMISSION_ASSIGN',

  // AUDIT LOG
  AUDIT_LOG_READ: 'AUDIT_LOG_READ',

  // WALLET
  WALLET_READ: 'WALLET_READ',
  WALLET_CREATE: 'WALLET_CREATE',
  WALLET_UPDATE: 'WALLET_UPDATE',
  WALLET_DELETE: 'WALLET_DELETE',

  // TRANSACTION
  TRANSACTION_READ: 'TRANSACTION_READ',
  TRANSACTION_CREATE: 'TRANSACTION_CREATE',
  TRANSACTION_UPDATE: 'TRANSACTION_UPDATE',
  TRANSACTION_DELETE: 'TRANSACTION_DELETE',

  // TRANSFER
  TRANSFER_READ: 'TRANSFER_READ',
  TRANSFER_CREATE: 'TRANSFER_CREATE',
  TRANSFER_DELETE: 'TRANSFER_DELETE',

  // CATEGORY
  CATEGORY_READ: 'CATEGORY_READ',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',

  // BUDGET
  BUDGET_READ: 'BUDGET_READ',
  BUDGET_CREATE: 'BUDGET_CREATE',
  BUDGET_UPDATE: 'BUDGET_UPDATE',
  BUDGET_DELETE: 'BUDGET_DELETE',

  // SAVING GOAL
  SAVING_GOAL_READ: 'SAVING_GOAL_READ',
  SAVING_GOAL_CREATE: 'SAVING_GOAL_CREATE',
  SAVING_GOAL_UPDATE: 'SAVING_GOAL_UPDATE',
  SAVING_GOAL_DELETE: 'SAVING_GOAL_DELETE',

  // REPORT
  REPORT_READ: 'REPORT_READ',

  // FORECAST
  FORECAST_READ: 'FORECAST_READ',

  // SIMULATION
  SIMULATION_READ: 'SIMULATION_READ',
  SIMULATION_EXECUTE: 'SIMULATION_EXECUTE',

  // ANOMALY
  ANOMALY_READ: 'ANOMALY_READ',
  ANOMALY_EVALUATE: 'ANOMALY_EVALUATE',

  // SUBSCRIPTION
  SUBSCRIPTION_READ: 'SUBSCRIPTION_READ',
  SUBSCRIPTION_MANAGE: 'SUBSCRIPTION_MANAGE',

  // QUERY
  QUERY_EXECUTE: 'QUERY_EXECUTE',

  // RECURRING TRANSACTION
  RECURRING_TRANSACTION_READ: 'RECURRING_TRANSACTION_READ',
  RECURRING_TRANSACTION_CREATE: 'RECURRING_TRANSACTION_CREATE',
  RECURRING_TRANSACTION_UPDATE: 'RECURRING_TRANSACTION_UPDATE',
  RECURRING_TRANSACTION_DELETE: 'RECURRING_TRANSACTION_DELETE',

  // NOTIFICATION
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  NOTIFICATION_UPDATE: 'NOTIFICATION_UPDATE',
  NOTIFICATION_DELETE: 'NOTIFICATION_DELETE',
  NOTIFICATION_ADMIN_READ: 'NOTIFICATION_ADMIN_READ',
  NOTIFICATION_RETRY: 'NOTIFICATION_RETRY',
  NOTIFICATION_TEMPLATE_READ: 'NOTIFICATION_TEMPLATE_READ',
  NOTIFICATION_TEMPLATE_UPDATE: 'NOTIFICATION_TEMPLATE_UPDATE',
  NOTIFICATION_CONFIG_UPDATE: 'NOTIFICATION_CONFIG_UPDATE',

  // REMINDER
  REMINDER_READ: 'REMINDER_READ',
  REMINDER_CREATE: 'REMINDER_CREATE',
  REMINDER_UPDATE: 'REMINDER_UPDATE',
  REMINDER_DELETE: 'REMINDER_DELETE',

  // AI ASSISTANT & AI ADMIN
  AI_ASSISTANT_USE: 'AI_ASSISTANT_USE',
  AI_ADMIN_READ: 'AI_ADMIN_READ',
  AI_CONFIG_UPDATE: 'AI_CONFIG_UPDATE',
  AI_USAGE_READ: 'AI_USAGE_READ',

  // SYSTEM CONFIGURATION & MAINTENANCE
  SYSTEM_CONFIG_READ: 'SYSTEM_CONFIG_READ',
  SYSTEM_CONFIG_UPDATE: 'SYSTEM_CONFIG_UPDATE',
  MAINTENANCE_MODE_UPDATE: 'MAINTENANCE_MODE_UPDATE',

  // UPLOAD
  UPLOAD_FILE: 'UPLOAD_FILE',

  // API KEY INTEGRATION
  API_KEY_READ: 'API_KEY_READ',
  API_KEY_CREATE: 'API_KEY_CREATE',
  API_KEY_DELETE: 'API_KEY_DELETE',

  // WEBHOOK INTEGRATION
  WEBHOOK_READ: 'WEBHOOK_READ',
  WEBHOOK_CREATE: 'WEBHOOK_CREATE',
  WEBHOOK_UPDATE: 'WEBHOOK_UPDATE',
  WEBHOOK_DELETE: 'WEBHOOK_DELETE',
  WEBHOOK_TEST: 'WEBHOOK_TEST',

  // ASYNC JOB
  JOB_READ: 'JOB_READ',
  JOB_CREATE: 'JOB_CREATE',

  // STATEMENT EXPORT
  STATEMENT_READ: 'STATEMENT_READ',
  STATEMENT_EXPORT: 'STATEMENT_EXPORT',
} as const;

export type PermissionName = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

